name: Frontend workflow

env:
  IMAGE_TAG: ${{ github.sha }}

on:
  push

jobs:
  Push-of-Docker-Image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build of docker image
        run : |
          docker build -t terezabisharyan/app-frontend:$IMAGE_TAG ./client/

      - name: Push image on DockerHub
        run : |
          docker login -u terezabisharyan -p ${{ secrets.DOCKER_PASSWORD }}
          docker push terezabisharyan/app-client:$IMAGE_TAG
